<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class PermissionsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('permissions')->delete();

        \DB::table('permissions')->insert([
            [
                'id' => 1,
                'name' => 'create-user',
                'guard_name' => 'web',
                'created_at' => '2023-04-13 07:02:18',
                'updated_at' => '2023-04-13 07:02:18',
                'group' => 'User',
            ],
            [
                'id' => 2,
                'name' => 'read-user',
                'guard_name' => 'web',
                'created_at' => '2023-04-13 07:02:27',
                'updated_at' => '2023-04-13 07:02:27',
                'group' => 'User',
            ],
            [
                'id' => 3,
                'name' => 'update-user',
                'guard_name' => 'web',
                'created_at' => '2023-04-13 07:02:34',
                'updated_at' => '2023-04-13 07:02:34',
                'group' => 'User',
            ],
            [
                'id' => 4,
                'name' => 'delete-user',
                'guard_name' => 'web',
                'created_at' => '2023-04-13 07:02:41',
                'updated_at' => '2023-04-13 07:02:41',
                'group' => 'User',
            ],
            [
                'id' => 5,
                'name' => 'create-role',
                'guard_name' => 'web',
                'created_at' => '2023-04-13 07:02:50',
                'updated_at' => '2023-04-13 07:02:50',
                'group' => 'Role',
            ],
            [
                'id' => 6,
                'name' => 'read-role',
                'guard_name' => 'web',
                'created_at' => '2023-04-13 07:02:55',
                'updated_at' => '2023-04-13 07:02:55',
                'group' => 'Role',
            ],
            [
                'id' => 7,
                'name' => 'update-role',
                'guard_name' => 'web',
                'created_at' => '2023-04-13 07:03:28',
                'updated_at' => '2023-04-13 07:03:28',
                'group' => 'Role',
            ],
            [
                'id' => 8,
                'name' => 'delete-role',
                'guard_name' => 'web',
                'created_at' => '2023-04-13 07:03:34',
                'updated_at' => '2023-04-13 07:03:34',
                'group' => 'Role',
            ],
            [
                'id' => 9,
                'name' => 'create-permission',
                'guard_name' => 'web',
                'created_at' => '2023-04-13 07:04:19',
                'updated_at' => '2023-04-13 07:04:19',
                'group' => 'Permission',
            ],
            [
                'id' => 10,
                'name' => 'read-permission',
                'guard_name' => 'web',
                'created_at' => '2023-04-13 07:04:27',
                'updated_at' => '2023-04-13 07:04:27',
                'group' => 'Permission',
            ],
            [
                'id' => 11,
                'name' => 'update-permission',
                'guard_name' => 'web',
                'created_at' => '2023-04-13 07:04:36',
                'updated_at' => '2023-04-13 07:04:36',
                'group' => 'Permission',
            ],
            [
                'id' => 12,
                'name' => 'delete-permission',
                'guard_name' => 'web',
                'created_at' => '2023-04-13 07:04:42',
                'updated_at' => '2023-04-13 07:04:42',
                'group' => 'Permission',
            ],
            [
                'id' => 13,
                'name' => 'create-menu',
                'guard_name' => 'web',
                'created_at' => '2023-04-13 08:15:00',
                'updated_at' => '2023-04-13 08:15:00',
                'group' => 'Menu',
            ],
            [
                'id' => 14,
                'name' => 'read-menu',
                'guard_name' => 'web',
                'created_at' => '2023-04-13 08:15:00',
                'updated_at' => '2023-04-13 08:15:00',
                'group' => 'Menu',
            ],
            [
                'id' => 15,
                'name' => 'update-menu',
                'guard_name' => 'web',
                'created_at' => '2023-04-13 08:15:00',
                'updated_at' => '2023-04-13 08:15:00',
                'group' => 'Menu',
            ],
            [
                'id' => 16,
                'name' => 'delete-menu',
                'guard_name' => 'web',
                'created_at' => '2023-04-13 08:15:00',
                'updated_at' => '2023-04-13 08:15:00',
                'group' => 'Menu',
            ],
            [
                'id' => 17,
                'name' => 'create-setting',
                'guard_name' => 'web',
                'created_at' => '2023-04-24 07:47:09',
                'updated_at' => '2023-04-24 07:47:09',
                'group' => 'Setting',
            ],
            [
                'id' => 18,
                'name' => 'read-setting',
                'guard_name' => 'web',
                'created_at' => '2023-04-24 07:47:20',
                'updated_at' => '2023-04-24 07:47:20',
                'group' => 'Setting',
            ],
            [
                'id' => 19,
                'name' => 'update-setting',
                'guard_name' => 'web',
                'created_at' => '2023-04-24 07:47:31',
                'updated_at' => '2023-04-24 07:47:31',
                'group' => 'Setting',
            ],
            [
                'id' => 20,
                'name' => 'delete-setting',
                'guard_name' => 'web',
                'created_at' => '2023-04-24 07:47:40',
                'updated_at' => '2023-04-24 07:47:40',
                'group' => 'Setting',
            ],
            [
                'id' => 21,
                'name' => 'create-item-type',
                'guard_name' => 'web',
                'created_at' => '2025-01-05 14:20:54',
                'updated_at' => '2025-01-05 14:20:54',
                'group' => 'ItemType',
            ],
            [
                'id' => 22,
                'name' => 'read-item-type',
                'guard_name' => 'web',
                'created_at' => '2025-01-05 14:20:56',
                'updated_at' => '2025-01-05 14:20:56',
                'group' => 'ItemType',
            ],
            [
                'id' => 23,
                'name' => 'update-item-type',
                'guard_name' => 'web',
                'created_at' => '2025-01-05 14:20:56',
                'updated_at' => '2025-01-05 14:20:56',
                'group' => 'ItemType',
            ],
            [
                'id' => 24,
                'name' => 'delete-item-type',
                'guard_name' => 'web',
                'created_at' => '2025-01-05 14:20:56',
                'updated_at' => '2025-01-05 14:20:56',
                'group' => 'ItemType',
            ],
            [
                'id' => 25,
                'name' => 'create-item-category',
                'guard_name' => 'web',
                'created_at' => '2025-01-05 15:31:16',
                'updated_at' => '2025-01-05 15:31:16',
                'group' => 'ItemCategory',
            ],
            [
                'id' => 26,
                'name' => 'read-item-category',
                'guard_name' => 'web',
                'created_at' => '2025-01-05 15:31:17',
                'updated_at' => '2025-01-05 15:31:17',
                'group' => 'ItemCategory',
            ]
        ]);
        \DB::table('permissions')->insert(
            [
                [
                    'id' => 27,
                    'name' => 'update-item-category',
                    'guard_name' => 'web',
                    'created_at' => '2025-01-05 15:31:17',
                    'updated_at' => '2025-01-05 15:31:17',
                    'group' => 'ItemCategory',
                ],
                [
                    'id' => 28,
                    'name' => 'delete-item-category',
                    'guard_name' => 'web',
                    'created_at' => '2025-01-05 15:31:17',
                    'updated_at' => '2025-01-05 15:31:17',
                    'group' => 'ItemCategory',
                ],
                [
                    'id' => 29,
                    'name' => 'create-unit-of-measurement',
                    'guard_name' => 'web',
                    'created_at' => '2025-01-05 16:38:48',
                    'updated_at' => '2025-01-05 16:38:48',
                    'group' => 'UnitOfMeasurement',
                ],
                [
                    'id' => 30,
                    'name' => 'read-unit-of-measurement',
                    'guard_name' => 'web',
                    'created_at' => '2025-01-05 16:38:49',
                    'updated_at' => '2025-01-05 16:38:49',
                    'group' => 'UnitOfMeasurement',
                ],
                [
                    'id' => 31,
                    'name' => 'update-unit-of-measurement',
                    'guard_name' => 'web',
                    'created_at' => '2025-01-05 16:38:49',
                    'updated_at' => '2025-01-05 16:38:49',
                    'group' => 'UnitOfMeasurement',
                ],
                [
                    'id' => 32,
                    'name' => 'delete-unit-of-measurement',
                    'guard_name' => 'web',
                    'created_at' => '2025-01-05 16:38:49',
                    'updated_at' => '2025-01-05 16:38:49',
                    'group' => 'UnitOfMeasurement',
                ],
                [
                    'id' => 33,
                    'name' => 'create-item',
                    'guard_name' => 'web',
                    'created_at' => '2025-01-05 18:38:22',
                    'updated_at' => '2025-01-05 18:38:22',
                    'group' => 'Item',
                ],
                [
                    'id' => 34,
                    'name' => 'read-item',
                    'guard_name' => 'web',
                    'created_at' => '2025-01-05 18:38:24',
                    'updated_at' => '2025-01-05 18:38:24',
                    'group' => 'Item',
                ],
                [
                    'id' => 35,
                    'name' => 'update-item',
                    'guard_name' => 'web',
                    'created_at' => '2025-01-05 18:38:24',
                    'updated_at' => '2025-01-05 18:38:24',
                    'group' => 'Item',
                ],
                [
                    'id' => 36,
                    'name' => 'delete-item',
                    'guard_name' => 'web',
                    'created_at' => '2025-01-05 18:38:24',
                    'updated_at' => '2025-01-05 18:38:24',
                    'group' => 'Item',
                ],
                [
                    'id' => 37,
                    'name' => 'create-item-uom',
                    'guard_name' => 'web',
                    'created_at' => '2025-01-05 18:38:51',
                    'updated_at' => '2025-01-05 18:38:51',
                    'group' => 'ItemUom',
                ],
                [
                    'id' => 38,
                    'name' => 'read-item-uom',
                    'guard_name' => 'web',
                    'created_at' => '2025-01-05 18:38:53',
                    'updated_at' => '2025-01-05 18:38:53',
                    'group' => 'ItemUom',
                ],
                [
                    'id' => 39,
                    'name' => 'update-item-uom',
                    'guard_name' => 'web',
                    'created_at' => '2025-01-05 18:38:53',
                    'updated_at' => '2025-01-05 18:38:53',
                    'group' => 'ItemUom',
                ],
                [
                    'id' => 40,
                    'name' => 'delete-item-uom',
                    'guard_name' => 'web',
                    'created_at' => '2025-01-05 18:38:53',
                    'updated_at' => '2025-01-05 18:38:53',
                    'group' => 'ItemUom',
                ],
                [
                    'id' => 41,
                    'name' => 'create-item-price-history',
                    'guard_name' => 'web',
                    'created_at' => '2025-01-05 18:39:24',
                    'updated_at' => '2025-01-05 18:39:24',
                    'group' => 'ItemPriceHistory',
                ],
                [
                    'id' => 42,
                    'name' => 'read-item-price-history',
                    'guard_name' => 'web',
                    'created_at' => '2025-01-05 18:39:25',
                    'updated_at' => '2025-01-05 18:39:25',
                    'group' => 'ItemPriceHistory',
                ],
                [
                    'id' => 43,
                    'name' => 'update-item-price-history',
                    'guard_name' => 'web',
                    'created_at' => '2025-01-05 18:39:25',
                    'updated_at' => '2025-01-05 18:39:25',
                    'group' => 'ItemPriceHistory',
                ],
                [
                    'id' => 44,
                    'name' => 'delete-item-price-history',
                    'guard_name' => 'web',
                    'created_at' => '2025-01-05 18:39:25',
                    'updated_at' => '2025-01-05 18:39:25',
                    'group' => 'ItemPriceHistory',
                ],
                [
                    'id' => 45,
                    'name' => 'create-customer',
                    'guard_name' => 'web',
                    'created_at' => '2025-01-06 01:20:48',
                    'updated_at' => '2025-01-06 01:20:48',
                    'group' => 'Customer',
                ],
                [
                    'id' => 46,
                    'name' => 'read-customer',
                    'guard_name' => 'web',
                    'created_at' => '2025-01-06 01:20:51',
                    'updated_at' => '2025-01-06 01:20:51',
                    'group' => 'Customer',
                ],
                [
                    'id' => 47,
                    'name' => 'update-customer',
                    'guard_name' => 'web',
                    'created_at' => '2025-01-06 01:20:51',
                    'updated_at' => '2025-01-06 01:20:51',
                    'group' => 'Customer',
                ],
                [
                    'id' => 48,
                    'name' => 'delete-customer',
                    'guard_name' => 'web',
                    'created_at' => '2025-01-06 01:20:51',
                    'updated_at' => '2025-01-06 01:20:51',
                    'group' => 'Customer',
                ],
            ]
        );
        \DB::table('permissions')->insert([
            [
                'id' => 49,
                'name' => 'create-file',
                'guard_name' => 'web',
                'created_at' => '2025-01-07 02:12:04',
                'updated_at' => '2025-01-07 02:12:04',
                'group' => 'File',
            ],
            [
                'id' => 50,
                'name' => 'read-file',
                'guard_name' => 'web',
                'created_at' => '2025-01-07 02:12:07',
                'updated_at' => '2025-01-07 02:12:07',
                'group' => 'File',
            ],
            [
                'id' => 51,
                'name' => 'update-file',
                'guard_name' => 'web',
                'created_at' => '2025-01-07 02:12:07',
                'updated_at' => '2025-01-07 02:12:07',
                'group' => 'File',
            ],
            [
                'id' => 52,
                'name' => 'delete-file',
                'guard_name' => 'web',
                'created_at' => '2025-01-07 02:12:07',
                'updated_at' => '2025-01-07 02:12:07',
                'group' => 'File',
            ],
            [
                'id' => 53,
                'name' => 'create-job-category',
                'guard_name' => 'web',
                'created_at' => '2025-01-07 04:32:57',
                'updated_at' => '2025-01-07 04:32:57',
                'group' => 'JobCategory',
            ],
            [
                'id' => 54,
                'name' => 'read-job-category',
                'guard_name' => 'web',
                'created_at' => '2025-01-07 04:32:58',
                'updated_at' => '2025-01-07 04:32:58',
                'group' => 'JobCategory',
            ],
            [
                'id' => 55,
                'name' => 'update-job-category',
                'guard_name' => 'web',
                'created_at' => '2025-01-07 04:32:58',
                'updated_at' => '2025-01-07 04:32:58',
                'group' => 'JobCategory',
            ],
            [
                'id' => 56,
                'name' => 'delete-job-category',
                'guard_name' => 'web',
                'created_at' => '2025-01-07 04:32:58',
                'updated_at' => '2025-01-07 04:32:58',
                'group' => 'JobCategory',
            ],
            [
                'id' => 57,
                'name' => 'create-customer-order',
                'guard_name' => 'web',
                'created_at' => '2025-01-07 05:05:56',
                'updated_at' => '2025-01-07 05:05:56',
                'group' => 'CustomerOrder',
            ],
            [
                'id' => 58,
                'name' => 'read-customer-order',
                'guard_name' => 'web',
                'created_at' => '2025-01-07 05:05:57',
                'updated_at' => '2025-01-07 05:05:57',
                'group' => 'CustomerOrder',
            ],
            [
                'id' => 59,
                'name' => 'update-customer-order',
                'guard_name' => 'web',
                'created_at' => '2025-01-07 05:05:57',
                'updated_at' => '2025-01-07 05:05:57',
                'group' => 'CustomerOrder',
            ],
            [
                'id' => 60,
                'name' => 'delete-customer-order',
                'guard_name' => 'web',
                'created_at' => '2025-01-07 05:05:57',
                'updated_at' => '2025-01-07 05:05:57',
                'group' => 'CustomerOrder',
            ],
        ]);

        \DB::table('permissions')->insert([
            [
                'id' => 61,
                'name' => 'create-item-request',
                'guard_name' => 'web',
                'created_at' => '2025-01-13 14:26:05',
                'updated_at' => '2025-01-13 14:26:05',
                'group' => 'ItemRequest',
            ],
            [
                'id' => 62,
                'name' => 'read-item-request',
                'guard_name' => 'web',
                'created_at' => '2025-01-13 14:26:06',
                'updated_at' => '2025-01-13 14:26:06',
                'group' => 'ItemRequest',
            ],
            [
                'id' => 63,
                'name' => 'update-item-request',
                'guard_name' => 'web',
                'created_at' => '2025-01-13 14:26:06',
                'updated_at' => '2025-01-13 14:26:06',
                'group' => 'ItemRequest',
            ],
            [
                'id' => 64,
                'name' => 'delete-item-request',
                'guard_name' => 'web',
                'created_at' => '2025-01-13 14:26:06',
                'updated_at' => '2025-01-13 14:26:06',
                'group' => 'ItemRequest',
            ],
            [
                'id' => 65,
                'name' => 'create-item-request-detail',
                'guard_name' => 'web',
                'created_at' => '2025-01-13 14:30:21',
                'updated_at' => '2025-01-13 14:30:21',
                'group' => 'ItemRequestDetail',
            ],
            [
                'id' => 66,
                'name' => 'read-item-request-detail',
                'guard_name' => 'web',
                'created_at' => '2025-01-13 14:30:22',
                'updated_at' => '2025-01-13 14:30:22',
                'group' => 'ItemRequestDetail',
            ],
            [
                'id' => 67,
                'name' => 'update-item-request-detail',
                'guard_name' => 'web',
                'created_at' => '2025-01-13 14:30:22',
                'updated_at' => '2025-01-13 14:30:22',
                'group' => 'ItemRequestDetail',
            ],
            [
                'id' => 68,
                'name' => 'delete-item-request-detail',
                'guard_name' => 'web',
                'created_at' => '2025-01-13 14:30:22',
                'updated_at' => '2025-01-13 14:30:22',
                'group' => 'ItemRequestDetail',
            ],
            [
                'id' => 69,
                'name' => 'create-approval',
                'guard_name' => 'web',
                'created_at' => '2025-01-14 01:18:07',
                'updated_at' => '2025-01-14 01:18:07',
                'group' => 'Approval',
            ],
            [
                'id' => 70,
                'name' => 'read-approval',
                'guard_name' => 'web',
                'created_at' => '2025-01-14 01:18:10',
                'updated_at' => '2025-01-14 01:18:10',
                'group' => 'Approval',
            ],
            [
                'id' => 71,
                'name' => 'update-approval',
                'guard_name' => 'web',
                'created_at' => '2025-01-14 01:18:10',
                'updated_at' => '2025-01-14 01:18:10',
                'group' => 'Approval',
            ],
            [
                'id' => 72,
                'name' => 'delete-approval',
                'guard_name' => 'web',
                'created_at' => '2025-01-14 01:18:10',
                'updated_at' => '2025-01-14 01:18:10',
                'group' => 'Approval',
            ],
            [
                'id' => 73,
                'name' => 'create-approval-level',
                'guard_name' => 'web',
                'created_at' => '2025-01-14 01:18:50',
                'updated_at' => '2025-01-14 01:18:50',
                'group' => 'ApprovalLevel',
            ],
        ]);
        \DB::table('permissions')->insert([
            [
                'id' => 74,
                'name' => 'read-approval-level',
                'guard_name' => 'web',
                'created_at' => '2025-01-14 01:18:51',
                'updated_at' => '2025-01-14 01:18:51',
                'group' => 'ApprovalLevel',
            ],
            [
                'id' => 75,
                'name' => 'update-approval-level',
                'guard_name' => 'web',
                'created_at' => '2025-01-14 01:18:51',
                'updated_at' => '2025-01-14 01:18:51',
                'group' => 'ApprovalLevel',
            ],
            [
                'id' => 76,
                'name' => 'delete-approval-level',
                'guard_name' => 'web',
                'created_at' => '2025-01-14 01:18:51',
                'updated_at' => '2025-01-14 01:18:51',
                'group' => 'ApprovalLevel',
            ],
            [
                'id' => 77,
                'name' => 'create-approval-request',
                'guard_name' => 'web',
                'created_at' => '2025-01-14 03:00:20',
                'updated_at' => '2025-01-14 03:00:20',
                'group' => 'ApprovalRequest',
            ],
            [
                'id' => 78,
                'name' => 'read-approval-request',
                'guard_name' => 'web',
                'created_at' => '2025-01-14 03:00:21',
                'updated_at' => '2025-01-14 03:00:21',
                'group' => 'ApprovalRequest',
            ],
            [
                'id' => 79,
                'name' => 'update-approval-request',
                'guard_name' => 'web',
                'created_at' => '2025-01-14 03:00:21',
                'updated_at' => '2025-01-14 03:00:21',
                'group' => 'ApprovalRequest',
            ],
            [
                'id' => 80,
                'name' => 'delete-approval-request',
                'guard_name' => 'web',
                'created_at' => '2025-01-14 03:00:21',
                'updated_at' => '2025-01-14 03:00:21',
                'group' => 'ApprovalRequest',
            ],
            [
                'id' => 81,
                'name' => 'create-approval-request-log',
                'guard_name' => 'web',
                'created_at' => '2025-01-14 03:01:52',
                'updated_at' => '2025-01-14 03:01:52',
                'group' => 'ApprovalRequestLog',
            ],
            [
                'id' => 82,
                'name' => 'read-approval-request-log',
                'guard_name' => 'web',
                'created_at' => '2025-01-14 03:01:55',
                'updated_at' => '2025-01-14 03:01:55',
                'group' => 'ApprovalRequestLog',
            ],
            [
                'id' => 83,
                'name' => 'update-approval-request-log',
                'guard_name' => 'web',
                'created_at' => '2025-01-14 03:01:55',
                'updated_at' => '2025-01-14 03:01:55',
                'group' => 'ApprovalRequestLog',
            ],
            [
                'id' => 84,
                'name' => 'delete-approval-request-log',
                'guard_name' => 'web',
                'created_at' => '2025-01-14 03:01:55',
                'updated_at' => '2025-01-14 03:01:55',
                'group' => 'ApprovalRequestLog',
            ],
            [
                'id' => 85,
                'name' => 'approve-delete-customer',
                'guard_name' => 'web',
                'created_at' => '2025-01-14 03:28:43',
                'updated_at' => '2025-01-14 03:28:43',
                'group' => 'Customer',
            ],
            [
                'id' => 86,
                'name' => 'approve-item-request',
                'guard_name' => 'web',
                'created_at' => '2025-01-14 06:16:04',
                'updated_at' => '2025-01-14 06:16:04',
                'group' => 'ItemRequest',
            ],
        ]);

        \DB::table('permissions')->insert([
            [
                'id' => 87,
                'name' => 'create-department',
                'guard_name' => 'web',
                'created_at' => '2025-02-02 23:50:50',
                'updated_at' => '2025-02-02 23:50:50',
                'group' => 'Department',
            ],
            [
                'id' => 88,
                'name' => 'read-department',
                'guard_name' => 'web',
                'created_at' => '2025-02-02 23:50:54',
                'updated_at' => '2025-02-02 23:50:54',
                'group' => 'Department',
            ],
            [
                'id' => 89,
                'name' => 'update-department',
                'guard_name' => 'web',
                'created_at' => '2025-02-02 23:50:54',
                'updated_at' => '2025-02-02 23:50:54',
                'group' => 'Department',
            ],
            [
                'id' => 90,
                'name' => 'delete-department',
                'guard_name' => 'web',
                'created_at' => '2025-02-02 23:50:54',
                'updated_at' => '2025-02-02 23:50:54',
                'group' => 'Department',
            ],
            [
                'id' => 91,
                'name' => 'approve-delete-customer-order',
                'guard_name' => 'web',
                'created_at' => '2025-02-03 13:24:02',
                'updated_at' => '2025-02-03 13:24:02',
                'group' => 'CustomerOrder',
            ],
        ]);
        \DB::table('permissions')->insert([
            [
                'id' => 92,
                'name' => 'create-supplier',
                'guard_name' => 'web',
                'created_at' => '2025-02-05 13:31:32',
                'updated_at' => '2025-02-05 13:31:32',
                'group' => 'Supplier',
            ],
            [
                'id' => 93,
                'name' => 'read-supplier',
                'guard_name' => 'web',
                'created_at' => '2025-02-05 13:31:36',
                'updated_at' => '2025-02-05 13:31:36',
                'group' => 'Supplier',
            ],
            [
                'id' => 94,
                'name' => 'update-supplier',
                'guard_name' => 'web',
                'created_at' => '2025-02-05 13:31:36',
                'updated_at' => '2025-02-05 13:31:36',
                'group' => 'Supplier',
            ],
            [
                'id' => 95,
                'name' => 'delete-supplier',
                'guard_name' => 'web',
                'created_at' => '2025-02-05 13:31:36',
                'updated_at' => '2025-02-05 13:31:36',
                'group' => 'Supplier',
            ],
            [
                'id' => 96,
                'name' => 'create-item-request-process',
                'guard_name' => 'web',
                'created_at' => '2025-02-05 14:31:01',
                'updated_at' => '2025-02-05 14:31:01',
                'group' => 'ItemRequestProcess',
            ],
            [
                'id' => 97,
                'name' => 'read-item-request-process',
                'guard_name' => 'web',
                'created_at' => '2025-02-05 14:31:02',
                'updated_at' => '2025-02-05 14:31:02',
                'group' => 'ItemRequestProcess',
            ],
            [
                'id' => 98,
                'name' => 'update-item-request-process',
                'guard_name' => 'web',
                'created_at' => '2025-02-05 14:31:03',
                'updated_at' => '2025-02-05 14:31:03',
                'group' => 'ItemRequestProcess',
            ],
            [
                'id' => 99,
                'name' => 'delete-item-request-process',
                'guard_name' => 'web',
                'created_at' => '2025-02-05 14:31:03',
                'updated_at' => '2025-02-05 14:31:03',
                'group' => 'ItemRequestProcess',
            ],
            [
                'id' => 100,
                'name' => 'create-warehouse',
                'guard_name' => 'web',
                'created_at' => '2025-02-05 14:32:45',
                'updated_at' => '2025-02-05 14:32:45',
                'group' => 'Warehouse',
            ],
            [
                'id' => 101,
                'name' => 'read-warehouse',
                'guard_name' => 'web',
                'created_at' => '2025-02-05 14:32:47',
                'updated_at' => '2025-02-05 14:32:47',
                'group' => 'Warehouse',
            ],
            [
                'id' => 102,
                'name' => 'update-warehouse',
                'guard_name' => 'web',
                'created_at' => '2025-02-05 14:32:47',
                'updated_at' => '2025-02-05 14:32:47',
                'group' => 'Warehouse',
            ],
            [
                'id' => 103,
                'name' => 'delete-warehouse',
                'guard_name' => 'web',
                'created_at' => '2025-02-05 14:32:47',
                'updated_at' => '2025-02-05 14:32:47',
                'group' => 'Warehouse',
            ],
            [
                'id' => 104,
                'name' => 'create-warehouse-section',
                'guard_name' => 'web',
                'created_at' => '2025-02-05 14:38:53',
                'updated_at' => '2025-02-05 14:38:53',
                'group' => 'WarehouseSection',
            ],
            [
                'id' => 105,
                'name' => 'read-warehouse-section',
                'guard_name' => 'web',
                'created_at' => '2025-02-05 14:38:54',
                'updated_at' => '2025-02-05 14:38:54',
                'group' => 'WarehouseSection',
            ],
        ]);

        \DB::table('permissions')->insert([
            [
                'id' => 106,
                'name' => 'update-warehouse-section',
                'guard_name' => 'web',
                'created_at' => '2025-02-05 14:38:54',
                'updated_at' => '2025-02-05 14:38:54',
                'group' => 'WarehouseSection',
            ],
            [
                'id' => 107,
                'name' => 'delete-warehouse-section',
                'guard_name' => 'web',
                'created_at' => '2025-02-05 14:38:54',
                'updated_at' => '2025-02-05 14:38:54',
                'group' => 'WarehouseSection',
            ],
            [
                'id' => 108,
                'name' => 'create-stock-entry',
                'guard_name' => 'web',
                'created_at' => '2025-02-10 02:14:56',
                'updated_at' => '2025-02-10 02:14:56',
                'group' => 'StockEntry',
            ],
            [
                'id' => 109,
                'name' => 'read-stock-entry',
                'guard_name' => 'web',
                'created_at' => '2025-02-10 02:14:59',
                'updated_at' => '2025-02-10 02:14:59',
                'group' => 'StockEntry',
            ],
            [
                'id' => 110,
                'name' => 'update-stock-entry',
                'guard_name' => 'web',
                'created_at' => '2025-02-10 02:14:59',
                'updated_at' => '2025-02-10 02:14:59',
                'group' => 'StockEntry',
            ],
            [
                'id' => 111,
                'name' => 'delete-stock-entry',
                'guard_name' => 'web',
                'created_at' => '2025-02-10 02:14:59',
                'updated_at' => '2025-02-10 02:14:59',
                'group' => 'StockEntry',
            ],
            [
                'id' => 112,
                'name' => 'create-delivery-order',
                'guard_name' => 'web',
                'created_at' => '2025-02-10 08:34:19',
                'updated_at' => '2025-02-10 08:34:19',
                'group' => 'DeliveryOrder',
            ],
            [
                'id' => 113,
                'name' => 'read-delivery-order',
                'guard_name' => 'web',
                'created_at' => '2025-02-10 08:34:23',
                'updated_at' => '2025-02-10 08:34:23',
                'group' => 'DeliveryOrder',
            ],
            [
                'id' => 114,
                'name' => 'update-delivery-order',
                'guard_name' => 'web',
                'created_at' => '2025-02-10 08:34:23',
                'updated_at' => '2025-02-10 08:34:23',
                'group' => 'DeliveryOrder',
            ],
            [
                'id' => 115,
                'name' => 'delete-delivery-order',
                'guard_name' => 'web',
                'created_at' => '2025-02-10 08:34:23',
                'updated_at' => '2025-02-10 08:34:23',
                'group' => 'DeliveryOrder',
            ],
            [
                'id' => 116,
                'name' => 'create-delivery-order-detail',
                'guard_name' => 'web',
                'created_at' => '2025-02-10 08:35:18',
                'updated_at' => '2025-02-10 08:35:18',
                'group' => 'DeliveryOrderDetail',
            ],
            [
                'id' => 117,
                'name' => 'read-delivery-order-detail',
                'guard_name' => 'web',
                'created_at' => '2025-02-10 08:35:19',
                'updated_at' => '2025-02-10 08:35:19',
                'group' => 'DeliveryOrderDetail',
            ],
            [
                'id' => 118,
                'name' => 'update-delivery-order-detail',
                'guard_name' => 'web',
                'created_at' => '2025-02-10 08:35:19',
                'updated_at' => '2025-02-10 08:35:19',
                'group' => 'DeliveryOrderDetail',
            ],
            [
                'id' => 119,
                'name' => 'delete-delivery-order-detail',
                'guard_name' => 'web',
                'created_at' => '2025-02-10 08:35:19',
                'updated_at' => '2025-02-10 08:35:19',
                'group' => 'DeliveryOrderDetail',
            ],
            [
                'id' => 120,
                'name' => 'approval-delivery-order',
                'guard_name' => 'web',
                'created_at' => '2025-02-10 08:34:19',
                'updated_at' => '2025-02-10 08:34:19',
                'group' => 'DeliveryOrder',
            ],
        ]);
        DB::table('permissions')->insert([
            [
                'id' => 121,
                'name' => 'read-item-need-to-purchase',
                'guard_name' => 'web',
                'created_at' => '2025-02-14 13:19:22',
                'updated_at' => '2025-02-14 13:19:22',
                'group' => 'ItemNeedToPurchase',
            ],
            [
                'id' => 122,
                'name' => 'update-item-need-to-purchase',
                'guard_name' => 'web',
                'created_at' => '2025-02-14 13:19:22',
                'updated_at' => '2025-02-14 13:19:22',
                'group' => 'ItemNeedToPurchase',
            ],
            [
                'id' => 123,
                'name' => 'delete-item-need-to-purchase',
                'guard_name' => 'web',
                'created_at' => '2025-02-14 13:19:22',
                'updated_at' => '2025-02-14 13:19:22',
                'group' => 'ItemNeedToPurchase',
            ],
            [
                'id' => 124,
                'name' => 'create-item-need-to-purchase-detail',
                'guard_name' => 'web',
                'created_at' => '2025-02-14 13:22:09',
                'updated_at' => '2025-02-14 13:22:09',
                'group' => 'ItemNeedToPurchaseDetail',
            ],
            [
                'id' => 125,
                'name' => 'read-item-need-to-purchase-detail',
                'guard_name' => 'web',
                'created_at' => '2025-02-14 13:22:10',
                'updated_at' => '2025-02-14 13:22:10',
                'group' => 'ItemNeedToPurchaseDetail',
            ],
            [
                'id' => 126,
                'name' => 'update-item-need-to-purchase-detail',
                'guard_name' => 'web',
                'created_at' => '2025-02-14 13:22:10',
                'updated_at' => '2025-02-14 13:22:10',
                'group' => 'ItemNeedToPurchaseDetail',
            ],
            [
                'id' => 127,
                'name' => 'delete-item-need-to-purchase-detail',
                'guard_name' => 'web',
                'created_at' => '2025-02-14 13:22:10',
                'updated_at' => '2025-02-14 13:22:10',
                'group' => 'ItemNeedToPurchaseDetail',
            ],
            [
                'id' => 128,
                'name' => 'approve-item-need-to-purchase',
                'guard_name' => 'web',
                'created_at' => '2025-02-14 16:18:42',
                'updated_at' => '2025-02-14 16:18:42',
                'group' => 'ItemNeedToPurchase',
            ],
            [
                'id' => 129,
                'name' => 'create-purchase-order',
                'guard_name' => 'web',
                'created_at' => '2025-02-14 16:55:21',
                'updated_at' => '2025-02-14 16:55:21',
                'group' => 'PurchaseOrder',
            ],
            [
                'id' => 130,
                'name' => 'read-purchase-order',
                'guard_name' => 'web',
                'created_at' => '2025-02-14 16:55:24',
                'updated_at' => '2025-02-14 16:55:24',
                'group' => 'PurchaseOrder',
            ],
            [
                'id' => 131,
                'name' => 'update-purchase-order',
                'guard_name' => 'web',
                'created_at' => '2025-02-14 16:55:24',
                'updated_at' => '2025-02-14 16:55:24',
                'group' => 'PurchaseOrder',
            ],
        ]);
        DB::table('permissions')->insert([
            [
                'id' => 132,
                'name' => 'delete-purchase-order',
                'guard_name' => 'web',
                'created_at' => '2025-02-14 16:55:24',
                'updated_at' => '2025-02-14 16:55:24',
                'group' => 'PurchaseOrder',
            ],
            [
                'id' => 133,
                'name' => 'create-purchase-order-detail',
                'guard_name' => 'web',
                'created_at' => '2025-02-14 16:57:15',
                'updated_at' => '2025-02-14 16:57:15',
                'group' => 'PurchaseOrderDetail',
            ],
            [
                'id' => 134,
                'name' => 'read-purchase-order-detail',
                'guard_name' => 'web',
                'created_at' => '2025-02-14 16:57:16',
                'updated_at' => '2025-02-14 16:57:16',
                'group' => 'PurchaseOrderDetail',
            ],
            [
                'id' => 135,
                'name' => 'update-purchase-order-detail',
                'guard_name' => 'web',
                'created_at' => '2025-02-14 16:57:16',
                'updated_at' => '2025-02-14 16:57:16',
                'group' => 'PurchaseOrderDetail',
            ],
            [
                'id' => 136,
                'name' => 'delete-purchase-order-detail',
                'guard_name' => 'web',
                'created_at' => '2025-02-14 16:57:16',
                'updated_at' => '2025-02-14 16:57:16',
                'group' => 'PurchaseOrderDetail',
            ],
            [
                'id' => 137,
                'name' => 'create-purchase-order-supplier-offer',
                'guard_name' => 'web',
                'created_at' => '2025-02-17 15:35:53',
                'updated_at' => '2025-02-17 15:35:53',
                'group' => 'PurchaseOrderSupplierOffer',
            ],
            [
                'id' => 138,
                'name' => 'read-purchase-order-supplier-offer',
                'guard_name' => 'web',
                'created_at' => '2025-02-17 15:35:56',
                'updated_at' => '2025-02-17 15:35:56',
                'group' => 'PurchaseOrderSupplierOffer',
            ],
            [
                'id' => 139,
                'name' => 'update-purchase-order-supplier-offer',
                'guard_name' => 'web',
                'created_at' => '2025-02-17 15:35:56',
                'updated_at' => '2025-02-17 15:35:56',
                'group' => 'PurchaseOrderSupplierOffer',
            ],
            [
                'id' => 140,
                'name' => 'delete-purchase-order-supplier-offer',
                'guard_name' => 'web',
                'created_at' => '2025-02-17 15:35:56',
                'updated_at' => '2025-02-17 15:35:56',
                'group' => 'PurchaseOrderSupplierOffer',
            ],
            [
                'id' => 141,
                'name' => 'create-purchase-order-supplier-offer-detail',
                'guard_name' => 'web',
                'created_at' => '2025-02-17 15:46:00',
                'updated_at' => '2025-02-17 15:46:00',
                'group' => 'PurchaseOrderSupplierOfferDetail',
            ],
            [
                'id' => 142,
                'name' => 'read-purchase-order-supplier-offer-detail',
                'guard_name' => 'web',
                'created_at' => '2025-02-17 15:46:02',
                'updated_at' => '2025-02-17 15:46:02',
                'group' => 'PurchaseOrderSupplierOfferDetail',
            ],
            [
                'id' => 143,
                'name' => 'update-purchase-order-supplier-offer-detail',
                'guard_name' => 'web',
                'created_at' => '2025-02-17 15:46:02',
                'updated_at' => '2025-02-17 15:46:02',
                'group' => 'PurchaseOrderSupplierOfferDetail',
            ],
            [
                'id' => 144,
                'name' => 'delete-purchase-order-supplier-offer-detail',
                'guard_name' => 'web',
                'created_at' => '2025-02-17 15:46:02',
                'updated_at' => '2025-02-17 15:46:02',
                'group' => 'PurchaseOrderSupplierOfferDetail',
            ],
        ]);
    }
}
